### ISSUE TITLE
unable to convert it to plain text

### ISSUE THREAD

**Issue by cualquiercosa327** [leoetlino/evfl#1]
Hello,i am trying to export to plain text the event files from 1 2 switch but i am unable.
I dont know if the fact the files are .bin files are related.
i upload the files
Thank you
[Eventos.zip](https://github.com/zeldamods/evfl/files/3808871/Eventos.zip)

**Comment by leoetlino** [comment]
Wrong repository. This repo is for the evfl library, and GitHub issues are used for actual bugs, not support requests.
